version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 4.a, < 5"
  - dependency-name: pytest
    versions:
    - ">= 5.a, < 6"
  - dependency-name: tox
    versions:
    - "> 3.14.0, < 4"
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.1
